#ifndef OPENPERIPH_CONFIG_H
#define OPENPERIPH_CONFIG_H

#include <stdint.h>

#define OPENPERIPH_ROLE_MASTER 1U
#define OPENPERIPH_ROLE_SLAVE 2U

#ifndef OPENPERIPH_ROLE
//#define OPENPERIPH_ROLE OPENPERIPH_ROLE_SLAVE
#define OPENPERIPH_ROLE OPENPERIPH_ROLE_MASTER
#endif

#ifndef OPENPERIPH_NODE_ADDR
//#define OPENPERIPH_NODE_ADDR 0x20U
#define OPENPERIPH_NODE_ADDR 0x1U
#endif

#ifndef OPENPERIPH_MASTER_ADDR
#define OPENPERIPH_MASTER_ADDR 0x01U
#endif

#define OPENPERIPH_RF_CHANNEL_DEFAULT 0x00U
#define OPENPERIPH_FEATURE_USB_BRIDGE 1U
#define OPENPERIPH_FEATURE_DISPLAY 1U

#define OPENPERIPH_EPD_PANEL_2IN13_V4   1U
#define OPENPERIPH_EPD_PANEL_5IN83_V2   2U
#define OPENPERIPH_EPD_PANEL_5IN83B_V2  3U

#ifndef OPENPERIPH_EPD_PANEL
// #define OPENPERIPH_EPD_PANEL OPENPERIPH_EPD_PANEL_2IN13_V4
#define OPENPERIPH_EPD_PANEL OPENPERIPH_EPD_PANEL_5IN83_V2
// #define OPENPERIPH_EPD_PANEL OPENPERIPH_EPD_PANEL_5IN83B_V2
#endif

#if (OPENPERIPH_EPD_PANEL != OPENPERIPH_EPD_PANEL_2IN13_V4) && \
    (OPENPERIPH_EPD_PANEL != OPENPERIPH_EPD_PANEL_5IN83_V2) && \
    (OPENPERIPH_EPD_PANEL != OPENPERIPH_EPD_PANEL_5IN83B_V2)
#error "Unsupported OPENPERIPH_EPD_PANEL selection."
#endif

#if OPENPERIPH_EPD_PANEL == OPENPERIPH_EPD_PANEL_2IN13_V4
#define OPENPERIPH_EPD_WIDTH_PX 122U
#define OPENPERIPH_EPD_HEIGHT_PX 250U
#define OPENPERIPH_EPD_HAS_ACCENT_PLANE 0U
#elif OPENPERIPH_EPD_PANEL == OPENPERIPH_EPD_PANEL_5IN83_V2
#define OPENPERIPH_EPD_WIDTH_PX 648U
#define OPENPERIPH_EPD_HEIGHT_PX 480U
#define OPENPERIPH_EPD_HAS_ACCENT_PLANE 0U
#else
#define OPENPERIPH_EPD_WIDTH_PX 648U
#define OPENPERIPH_EPD_HEIGHT_PX 480U
#define OPENPERIPH_EPD_HAS_ACCENT_PLANE 1U
#endif

#define OPENPERIPH_EPD_STRIDE_BYTES ((OPENPERIPH_EPD_WIDTH_PX + 7U) / 8U)
#define OPENPERIPH_EPD_MONO_BUFFER_BYTES \
    (OPENPERIPH_EPD_STRIDE_BYTES * OPENPERIPH_EPD_HEIGHT_PX)

#ifndef OPENPERIPH_EPD_DEBUG
#define OPENPERIPH_EPD_DEBUG 0U
#endif

#ifndef OPENPERIPH_EPD_BUSY_TIMEOUT_MS
#define OPENPERIPH_EPD_BUSY_TIMEOUT_MS 5000U
#endif

#endif
