#ifndef OPENPERIPH_CONFIG_H
#define OPENPERIPH_CONFIG_H

#include <stdint.h>

#define OPENPERIPH_ROLE_MASTER 1U
#define OPENPERIPH_ROLE_SLAVE 2U

#ifndef OPENPERIPH_ROLE
#define OPENPERIPH_ROLE OPENPERIPH_ROLE_MASTER
#endif

#ifndef OPENPERIPH_NODE_ADDR
#define OPENPERIPH_NODE_ADDR 0x01U
#endif

#define OPENPERIPH_RF_CHANNEL_DEFAULT 0x00U
#define OPENPERIPH_FEATURE_USB_BRIDGE 1U
#define OPENPERIPH_FEATURE_DISPLAY 1U

#endif
